name: Lint markdown files
on:
  pull_request:
jobs:
  lint-markdown-files:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: "**/*.md"
        continue-on-error: false
